version: "2"

services:
  rabbitmq-stream:
    image: rabbitmq:3-management
    container_name: rabbitmq-stream
    restart: unless-stopped
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5552:5552"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
    volumes:
      - ../conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
